# Usa una imagen base de Java
FROM openjdk:17-jdk-alpine

# Configura el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo JAR de la aplicación al contenedor
COPY target/apidiaslaborales-0.0.1-SNAPSHOT.jar app.jar

# Expone el puerto que utiliza la aplicación Spring Boot
EXPOSE 7171

# Define el comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
